# name: binder
# channels:
#   - pytorch
#   - anaconda
#   - conda-forge
# dependencies:
#   - cudatoolkit=10.1
#   - tensorflow-gpu
# #   - torchvision
# #   - matplotlib==2.0.2
# #   - numpy==1.14.1
# #   - ipython==6.2.1
# #   - scikit-learn==0.19.1
