#!/bin/bash

# Allow drivers installed by the nvidia-driver-installer to be located
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/nvidia/lib64:/usr/local/nvidia/lib64:/usr/lib/x86_64-linux-gnu:/usr/local/cuda-10.1/targets/x86_64-linux/lib
# Also, utilities like `nvidia-smi` are installed here
export PATH=${PATH}:/usr/local/nvidia/bin:/usr/local/nvidia/bin:/usr/bin

exec "$@"
